language: go

go:
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"
  - "1.12"
  - "1.13"

install: 
- go get github.com/fvbock/endless
- go get github.com/jpillora/overseer
- go get github.com/karldoenitz/Tigo/TigoWeb
